# Python Data Analysis (Numpy, Pandas, Matplotlib, seaborn)

## NumPy Library

### numpy array

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
numArray = np.array([2,4,6,8]) # place in variable
numArray

array([2, 4, 6, 8])

In [4]:
floatArray = np.array([2.3,3.2,4.6,7.2])
floatArray

array([2.3, 3.2, 4.6, 7.2])

### array indexing

In [5]:
numArray[3]

8

In [6]:
numArray[-1] # reverse index

8

In [7]:
numArray[2:]

array([6, 8])

In [8]:
numArray[0::2] # [start:end:step]

array([2, 6])

In [9]:
numArray[1], numArray[2] # multiple index

(4, 6)

### array data type

In [10]:
numArray.dtype

dtype('int32')

In [11]:
floatArray.dtype

dtype('float64')

In [14]:
np.array([1,2,3,4,5], dtype=np.int16) # declaring data type in parameter

array([1, 2, 3, 4, 5], dtype=int16)

In [17]:
np.array([2.3,3.2,4.6,7.2], dtype=float)

array([2.3, 3.2, 4.6, 7.2])

### dimension & shape

In [19]:
# 2d array
twoDim = np.array([
    [3,2,1],
    [4,5,6]
])

twoDim

array([[3, 2, 1],
       [4, 5, 6]])

In [20]:
twoDim.shape # (rows, columns)

(2, 3)

In [21]:
twoDim.ndim # array dimension

2

In [22]:
twoDim.size # element size

6

In [23]:
# 3d array
threeDim = np.array([
    [
        [11,22,33],
        [10,20,30]
    ],
    [
        [40,50,60],
        [300,200,100]
    ]
])

threeDim

array([[[ 11,  22,  33],
        [ 10,  20,  30]],

       [[ 40,  50,  60],
        [300, 200, 100]]])

In [28]:
threeDim.dtype

dtype('int32')

In [24]:
threeDim.shape

(2, 2, 3)

In [26]:
threeDim.ndim

3

In [27]:
threeDim.size

12

### indexing and slicing matrices

In [29]:
# 3x3 matrix
matrix2D = np.array([
    [1,2,3],
    [10,20,30],
    [8,9,10]
])

matrix2D

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 8,  9, 10]])

In [30]:
matrix2D[1] # access rows

array([10, 20, 30])

In [31]:
matrix2D[0][2] # access intersection of row and column

3

In [32]:
matrix2D[2, 1] # access multiple dimension [rows, columns]

9

In [34]:
matrix2D[1:, 1:]

array([[20, 30],
       [ 9, 10]])

In [36]:

matrix2D[0] = np.array([11,22,33])
matrix2D

array([[11, 22, 33],
       [10, 20, 30],
       [ 8,  9, 10]])